### PR TITLE
Added feature to let user indicate ESSID when missing from pcap file …

### PR DESCRIPTION
**Pull request by gcarmix**
Added feature to let user indicate ESSID when missing from pcap file (cloaked ESSID).

When working with cloaked ESSID the Beacon packet does not contain the ESSID name necessary to generate the hash. With this new option it is now possible to manually add ESSID (taken from airodump, kismet...)

### CODE REVIEW

**Comment by s77rt** [comment]
Hi
Can you provide an example pcap file for that case?
Add zero padding to the essid.
This will overwrite every essid with the user specified one, not just the missing ones. 
Correct a typo on the help message. 
The argument name may need to be changed. It's confusing as it may suggest a filter functionality. `overwrite-essid` without a short form seems more suitable.

**Comment by gcarmix** [comment]
[cloaked_testwifi.pcap.zip](https://github.com/s77rt/multicapconverter/files/8543991/cloaked_testwifi.pcap.zip)
Hi,
I attached a sample pcap captured with kismet of a cloaked access point (the actual essid is "testwifi" and the password is "password" you can test on your own), 
I added zero padding, and renamed to --overwrite-essid as suggested.

**Comment by s77rt** [comment]
thanks, i think there is more can be done to make the code a bit more clear
1. the essid should be replaced with custom_essid only when essid_len is zero
2. `cloaked-essid` may be a better fit as the argument name in this case as not all the essids are overwriten.

**Comment by gcarmix** [comment]
for the first point I wouldn't do it, because some manufacturers implement the ESSID cloaking by zero-filling the field, like in the pcap below:
[cloaked_testwifi_2.pcap.zip](https://github.com/s77rt/multicapconverter/files/8546218/cloaked_testwifi_2.pcap.zip)
anyway I don't think that should be a problem since custom_essid variable is initialized to zero length, so it won't be used unless the user decides to use the option.

for the second point I agree with you, "cloaked-essid" option is more self-explicative

**Comment by s77rt** [comment]
thank you for your contribution.
I'm going to merge the pull request, although i will change the argument name back to `overwrite-essid` since that's exactly what's going on. `cloaked-essid` implements that only cloaked essids will be set, but actually it will overwrites all the essids in the network.

**Pull request merged**
